import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";
import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import AuthProvider from "./context/AuthProvider";

const instrument_sans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={instrument_sans.className}>
        <main>
          <AuthProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
